name=['A', 'B', 'C', 'D', 'E']
print(f"尊敬的{name[0]},我邀请你参加晚宴。")
print(f"尊敬的{name[2]},我邀请你参加晚宴。")
print(f"尊敬的{name[4]},我邀请你参加晚宴。")
print(f"很抱歉，{name[2]}不能参加晚宴。")
del name[2]
name.append('F')
print(f"尊敬的{name[0]},我邀请你参加晚宴。")
print(f"尊敬的{name[3]},我邀请你参加晚宴。")
print(f"尊敬的{name[4]},我邀请你参加晚宴。")
print("我找到了一张更大的餐桌，可以邀请更多人。")
name.insert(0,'G')
name.insert(2,'H')
name.append('I')
print(f"尊敬的{name[1]},我邀请你参加晚宴。")
print(f"尊敬的{name[5]},我邀请你参加晚宴。")
print(f"尊敬的{name[6]},我邀请你参加晚宴。")
print(f"尊敬的{name[0]},我邀请你参加晚宴。")
print(f"尊敬的{name[2]},我邀请你参加晚宴。")
print(f"尊敬的{name[-1]},我邀请你参加晚宴。")
print('非常抱歉，新购买的餐桌无法及时送达，因此只能邀请两位嘉宾。')
poped_name=name.pop(0)
print(f'{poped_name}，非常抱歉，不能邀请你参加晚宴了。')
poped_name=name.pop()
print(f'{poped_name}，非常抱歉，不能邀请你参加晚宴了。')
poped_name=name.pop()
print(f'{poped_name}，非常抱歉，不能邀请你参加晚宴了。')
poped_name=name.pop()
print(f'{poped_name}，非常抱歉，不能邀请你参加晚宴了。')
poped_name=name.pop()
print(f'{poped_name}，非常抱歉，不能邀请你参加晚宴了。')
poped_name=name.pop()
print(f'{poped_name}，非常抱歉，不能邀请你参加晚宴了。')
print(f"{name[0]},我邀请你参加晚宴。")
print(f"{name[1]},我邀请你参加晚宴。")
del name[0]
del name[0]
print(name)
print(len(name))